addons:
  apt:
    packages:
    - curl
    - libxml2-utils
    - pandoc
    - aspell
    - aspell-en
after_success:
- build/success.sh
before_install:
- sudo apt-get update -qq
language: python
python:
- '3.4'
script:
- rm -rf ./output
- rm -rf ./cache
- rm -rf ./plugins/*
- curl https://raw.githubusercontent.com/mike42/mdcheckr/master/mdcheckr -o mdcheckr
- chmod +x mdcheckr
- sudo cp mdcheckr /usr/local/bin
- git config user.email "frank378@gmail.com"
- git config user.name "@thedevilsvoice"
- build/validate_pr.sh
sudo: required
env:
  global:
    GH_TOKEN: 
      secure: OBsm/W8SG8cQlAr8lN+NDnDbX4N0SG7NmRvypYY6L+LoierXJZQner1gYWfeddCfyXv6jqhXkI81xLu5INNBakl3HifouAIzocEqq3EN/fjNZ0LN7p/oglexSiV+1Myw0buwQJ27Twv40Lobp6deV0tcv/1WwZ2h7HuMa4NWHetaDS5rmpT+ouUEz4gEW6sgDuDZCxkEHItgUd2vguiRtZo8uV1yUReGDr+J6aIl77sSeD9+J43YpLgGDL0YfV3td7zqecCoCDyHQ2W9ADFMQrg27ATE9nXzxSryLG+EcaGTmkDMannnxd/lWGuuoHIC9nWrFhZcffT5mdSzbgRu2PNG9gbcw7mgM8fcXnFJs9sPXX2itpmGsmNJzrxBXNGmEccNguVHGexMhK2PKpDslxOxFMSWi9NsvleV7iTgEPZW5mLw/JgIXoTBhkuHPjkIE4HlZ7BiVLWfVJA3k5+YPCM1DHin+0p5WeYSWZHxk7FkafBXW7Pv6E9rg7MZNR57fyHKdiMh5MFyICQLDBISkl65KQKGjaZNCfdcuA8yxr4kBEaygM/SCJazW2aJ/a9s+nAAFu2nPngC96ImpUPKt6M98yDVkNI78jsxXwZdHdR3TphSlOwJlecGhajoI+kFNj93cTogoenhWRm/+RSI34/8byRc+7V70RQ/4Wiu2LM=
