addons:
  apt:
    packages:
    - curl
    - libxml2-utils
    - pandoc
    - aspell
    - aspell-en
after_success:
- build/success.sh
before_install:
- sudo apt-get update -qq
language: python
python:
- '3.4'
script:
- rm -rf ./output
- rm -rf ./cache
- rm -rf ./plugins/*
- curl https://raw.githubusercontent.com/mike42/mdcheckr/master/mdcheckr -o mdcheckr
- chmod +x mdcheckr
- sudo cp mdcheckr /usr/local/bin
- "/usr/local/bin/mdcheckr -v"
- git config user.email "frank378@gmail.com"
- git config user.name "@thedevilsvoice"
- build/validate_pr.sh
sudo: required
env:
  global:
  - secure: "JEduVpR1291JVr6T0C/rCYAqlH0rgb6bYkXyWanQ+7KqDNXP6pcxUE6JKTlgdDYoxkww/Wzn2N1hozzseik23DwK7I3fcw0LBxlrXefQGM0uGtXBJHLamQdtOeeVsRkC+sx76bcwk5zgwDcM3N/I5yPabTw4D28/rJdeX5/khkv6rmApzgywFIXRlb9V3FvGI3OiVF3HG3vSNvZn4cqoKlmzbfizN8GVWOdxdITCvIsXv5Ph59hXkyR/XS6qqxj3JEggETELsXV9J7R4jNCZ7kpRWS8/9afrtx0ILofyU6sllS//UM9fuxatdwaJo6TiKXD3xFfTIWFAyHW7v8xUCk3o9BG4ozw3ZOAjv2PwxPbNrpldUgXYnjEVnxKM2fdBIxVeGt4KbTyDwOG4o3GTLxXLhi2aPB2WrjfSDgstr4iIFKvKXKiHU2iuNUG2d6W0PvjrQ7z3Zta/Uj+iuqGkNt0bd3EtuZD4BxLR94AnlQrjDkP9y0J7HiRfhR3SNRlhrgvOD0ubZcYIjFzM5vGbHbUVvLm1XTm0oFjuw+3+7UFoXeC/H523c6CKTHy0R99Dr1BkpE+ep8jeDUVHYnXi7mtu98kbDigjP4Er9IC2qJ3hG8wUKtTt/f1+UdS9bEpK+cWMAKuuqCLK+P+pvzK45Yeohbq8yQQ2CpNMoAnIR7Y="
