addons:
  apt:
    packages:
    - curl
    - libxml2-utils
    - pandoc
    - aspell
    - aspell-en
after_success:
- build/success.sh
before_install:
- sudo apt-get update -qq
language: python
python:
- '3.4'
script:
- 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash echo "PULL REQUEST: $TRAVIS_PULL_REQUEST"; fi'
- 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash  echo "NON PULL REQUEST"; fi'
- rm -rf ./output
- rm -rf ./cache
- rm -rf ./plugins/*
- curl https://raw.githubusercontent.com/mike42/mdcheckr/master/mdcheckr -o mdcheckr
- chmod +x mdcheckr
- sudo cp mdcheckr /usr/local/bin
- "/usr/local/bin/mdcheckr -v"
- git config user.email "frank378@gmail.com"
- git config user.name "@thedevilsvoice"
sudo: required
env:
  global:
  - secure: hIZQzfFOVm9MjxueEEYDfDETg6MpDJEfpinu+iAA0STVIqZaq85AIA8l7hc9AgqRrtz0PUPZAdLwYw0E8mYPaffXkPKRNAEUt4IlWJLMjOCJiZHo67oOWxop7p28dnD2c9dYqD4FKPnzJd40nM0yXWTcBsxqe7miBF+0em7Unh3JAF6z15yqWpTSA2M/noFuxN6IShkhp8EO4bt5j3dHBoqBEkizO6QeYIFLIoIkCdlFsujd5lMX3Ec1ydewkBIW7G1L8+IisBD0PhPv3LhqcyHpsTBgdTkxhdpCIeRw/6wll6z0QRcxkJDxrkTBfZWgZR5QkH09zj7UrPxckCpGwNtVJKXzbLvTZkWagpEH/fW1GW+I5E4UAS9AHvhbhViz1pJnKbmwLVfCvh4uO8odqjVhCTswLTHEx4k1aeLRvLPvscWBumatiGDtge+KKvBmAwdeH9nn7ej0mGmMh9vK6MVdLljBArc4HBkFtIxfT8Os1uWnFIbV8IBhSeVpMUwDoqRJsN0sKFiwaP0IKYcL7EuCaLZ/axCJ4AR6YAWKO2u8ynZsP4u/Y615dSXhRRDcAN1hJcSFURhM6K2qFo+nt43bwsH+A4zpMJF0gP0+0+LtGvtFB6e62+MAeWRb/McNSzXiktL422ATq5NVuU9Oi6zT1qbDgwCQDZo1YmeQQwc=
