--- 
addons: 
  apt: 
    packages: 
      - curl
      - libxml2-utils
      - pandoc
      - aspell
      - aspell-en
after_success: 
  - build/success.sh
before_install:
  - sudo apt-get update -qq
language: python
python: 
  - "3.4"
script: 
  - rm -rf ./output
  - rm -rf ./cache
  - rm -rf ./plugins/*
  - "curl https://raw.githubusercontent.com/mike42/mdcheckr/master/mdcheckr -o mdcheckr"
  - "chmod +x mdcheckr"
  - "sudo cp mdcheckr/mdcheckr /usr/local/bin"
  - git config user.email "frank378@gmail.com"
  - git config user.name "@thedevilsvoice"
  - rsync -rv --exclude=.git
  - build/validate_pr.sh
sudo: required
env: 
  global:
    secure: "fAfD7w+ZY8fT0qC2H5PCAz8iFL8LC1fhuZNYUtPtZqfBy7gqLZL5LbQsraPul1NciF+XiCvccBJDwVcZsKJKQ1MgcCeLOJ67PjKvat6/PttZS/d95709gZflJlVbK/RA5NPOw3n4shnwyRWAsvokQTJvMMoftHSV50Pm5tzFgrMBjMiKgTqnqJJhoWNzBwJP3FOgqdgU1odn3VZvBuKtWICnzUs/gpPJ1ukrIXiZAe7p5OI1dMQSyHYGByJNXIyGfvVqbCVmb978veLDSi6Ww4FA2jrUl7uWL4ln2xn9UmUy4RUKnf59YvOwSeQMN/XWMr2Ec4qkzC7oEuAmcopMl1ICDjdai07uLZVwK+0PD3PnXCyg4o3K0UdjXkrDHIxm5zW5Q69CeL81a7d0UmL5ZTv5sxmgOOuBsORXCvhbC53zTj6ZccNj5JlDmVBH+3iug+5xR3CG2a8qfNaxOJnHbts7ZqJaMPWeaRNQ6uC0PxSEQK4zHns2mS3uUPewP59HwfUENF9TdFPAzHAnLbAF5dVp8pj89Z7jpXuyCKMRGO9EyZ6Dx8HPa8EeL9EjnE4Vsdr0AA7zjGz8qAq+fMYdUE3ChVeKZ7tqXdQYQoI1mLlYCSYPwcxKg73Ru3y+LJzIrl1o7Ar1pWOaqfy0Rxca4VKgZlvHK/I8NKPWg0l9mxs="
